### ISSUE TITLE
Write a script to archive all team pages

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/aiwatch#142]
Pages can be archived by hitting `web.archive.org/save/<url>`. Write a script that reads in the `team_page` values from the `organizations` table and archives all of them. This script can be run a few times a month, either manually or in cron.

Also, confirm that the script works well and identify (and if possible mitigate) any issues such as rate-limiting, IP-blocking, etc.

**Comment by riceissa** [comment]
This script was working as of a few years ago: https://gitlab.com/orpheuslummis/archive-subwikis/-/blob/master/archive_subwikis.py#L27-36

**Comment by riceissa** [comment]
I have written an initial version at https://github.com/riceissa/aiwatch/commit/167c860c839702d532da5cfe39174c3938d77cab

**Comment by riceissa** [comment]
current version is at https://github.com/riceissa/aiwatch/blob/master/scripts/archive_team_pages.py

the script seems to work, and i've set it to run as a cronjob every week.
