### ISSUE TITLE
Add intersection views on Org Watch

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/aiwatch#15]
The ideas include:

- [x] A view for intersection of two organizations. This would show:
  - The people who have been involved with both orgs (not necessarily simultaneously)
  - The documents that involve both orgs, either as publisher or as affected organization
- [x] A view for things common between two people. This would show:
  - The organizations that both of them have been involved with (not necessarily simultaneously)
  - The documents that involve both people, either as author or as affected person

**Comment by riceissa** [comment]
This is mostly working now. Examples:

- https://orgwatch.issarice.com/intersect.php?organization1=Machine+Intelligence+Research+Institute&organization2=Open+Philanthropy+Project
- https://orgwatch.issarice.com/intersect.php?person1=Anna+Salamon&person2=Oliver+Habryka
