### ISSUE TITLE
Add org Legal Priorities Project

### ISSUE THREAD

**Issue by riceissa** [riceissa/aiwatch#43]
announced here: https://forum.effectivealtruism.org/posts/PvBLDPkqKvdHQkKPn/introducing-the-legal-priorities-project

**Comment by sebastiansanchez123** [comment]
I added 24 positions with both LinkedIn and Wayback snapshots. Ready to close issue.

**Comment by riceissa** [comment]
I checked several people and they all looked good except for the Habiba Islam thing I mentioned in chat. Happy to close once that is fixed.

**Comment by sebastiansanchez123** [comment]
Habiba Islam LinkedIn URL removed. Ready for review.

**Comment by riceissa** [comment]
Ok looks good, thanks!
