### ISSUE TITLE
some new hires at rethink priorities

### ISSUE THREAD

**Issue by riceissa** [riceissa/aiwatch#49]
https://forum.effectivealtruism.org/posts/33AnPajNYmNrdXQbj/rethink-priorities-2020-impact-and-2021-strategy

**Comment by sebastiansanchez123** [comment]
I created the file and added 24 positions. Ready for review.

**Comment by riceissa** [comment]
@sebastiansanchez123 It looks like you're using the URL https://www.rethinkpriorities.org/our-team for many of these positions, but team page content changes frequently so this link is pretty brittle. Can you make a fresh archive snapshot using https://web.archive.org/save/ or http://archive.is/ and use that URL instead?

**Comment by riceissa** [comment]
Oh wait, actually it looks like you already do use a Wayback snapshot on those. In that case I think you can just remove the https://www.rethinkpriorities.org/our-team URL.

**Comment by sebastiansanchez123** [comment]
Ok I will use only archive snapshots and remove the LinkedIn URL

**Comment by riceissa** [comment]
@sebastiansanchez123 The LinkedIn URLs are fine! It's just the current team page URL that's a problem.

**Comment by riceissa** [comment]
@sebastiansanchez123 Some info from the blog post in the original issue that I think should be incorporated:

* "in May [2020] we hired a Director of Operations, Abraham Rowe."
* "Peter Hurford, Co-Executive Director, became full-time in March 2020" (I think we should repeat the co-executive director row for peter, and say "part-time" in the first one and "full-time" in the second on for `employment_type` field)
* David Reinstein is listed as one of the new hires for 2020, so his `start_date` should be in 2020.

**Comment by sebastiansanchez123** [comment]
Ready

**Comment by riceissa** [comment]
Looks good, thanks!
