### ISSUE TITLE
Add org Generation Pledge

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/aiwatch#50]
Team page: https://www.generationpledge.org/team

Home page: https://www.generationpledge.org/

HT @riceissa

**Comment by sebastiansanchez123** [comment]
I created the file and added 11 positions. The org is new. It only has one blue dot on Wayback Machine. I used the actual org website and LinkedIn.  Ready for closure.

**Comment by riceissa** [comment]
@sebastiansanchez123 Instead of the live team page url, can you use a wayback snapshot url instead? I just made one at https://web.archive.org/web/20201216031319/https://www.generationpledge.org/team that you can use.

**Comment by riceissa** [comment]
Everything else looks good; happy to close once the url thing above is fixed!

**Comment by sebastiansanchez123** [comment]
Fixed. Ready for review.

**Comment by riceissa** [comment]
Looks good, thanks!
