### ISSUE TITLE
Add org High Impact Athletes

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/aiwatch#51]
https://highimpactathletes.com/team

Launch post: https://forum.effectivealtruism.org/posts/Fm3HWDZKtwdkvBzGL/introducing-high-impact-athletes

HT @riceissa

**Comment by sebastiansanchez123** [comment]
I created the file and added six positions, with URLs taken from Wayback snapshots and LinkedIn. Ready for closure.

**Comment by riceissa** [comment]
@sebastiansanchez123 Same problem here with the team page url https://highimpactathletes.com/team ; you already link to a Wayback snapshot of this url so it's not necessary.

**Comment by riceissa** [comment]
@sebastiansanchez123 You cite Josh Daniell's LinkedIn page https://www.linkedin.com/in/joshdaniell/ but I don't see anything about High Impact Athletes on it. Can you clarify or remove the link?

**Comment by riceissa** [comment]
Everything else looks good, so happy to merge once the above is fixed!

**Comment by sebastiansanchez123** [comment]
Fixed. Ready for review.

**Comment by riceissa** [comment]
Looks good, thanks!
