### ISSUE TITLE
On an organization page, have a programmatically populated section for "similar organizations"

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/aiwatch#52]
Make it show the list of organizations with the largest intersection size, along with intersection size and maybe intersection set 

And then link to the dedicated intersection pages created as part of #15.

Also maybe do something similar for person pages? Though it's less useful there, might still be interesting for duality reasons.

**Comment by riceissa** [comment]
This is now done. Examples:

* https://orgwatch.issarice.com/?organization=Machine+Intelligence+Research+Institute#similar-organizations
* https://orgwatch.issarice.com/?person=Anna+Salamon#similar-people
